#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"
#include "data-mov/push.h"
#include "data-mov/pop.h"
#include "data-mov/movzx.h"
#include "data-mov/movsx.h"
#include "data-mov/cmov.h"
#include "data-mov/lgdt.h"
#include "data-mov/lidt.h"
#include "data-mov/push_cs.h"
#include "data-mov/pusha.h"
#include "data-mov/popa.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"
#include "arith/sub.h"
#include "arith/cmp.h"
#include "arith/add.h"
#include "arith/adc.h"
#include "arith/sbb.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"
#include "logic/test.h"
#include "logic/sar.h"
#include "logic/set.h"
#include "logic/cltd.h"
#include "logic/cld.h"
#include "logic/cwd.h"
#include "logic/bt.h"
#include "logic/shld.h"

#include "string/rep.h"
#include "string/cmps.h"
#include "string/movs.h"
#include "string/stos.h"

#include "misc/misc.h"

#include "special/special.h"

#include "jumpjump/call.h"
#include "jumpjump/jcc.h"
#include "jumpjump/jmp.h"
#include "jumpjump/leave.h"
#include "jumpjump/ret.h"
#include "jumpjump/jecxz.h"

#include "io/in.h"
#include "io/out.h"
#include "io/hlt.h"

#include "intr/iret.h"
#include "intr/int.h"
